# Generated by Django 5.0 on 2023-12-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Input name of the Publisher", max_length=50
                    ),
                ),
                (
                    "website",
                    models.URLField(help_text="The Publishing company's website"),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="The publishing comapnys emails", max_length=254
                    ),
                ),
            ],
        ),
    ]
