# Generated by Django 5.0 on 2023-12-28 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Reviews", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="The contributors first name", max_length=50
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="The contributors last name", max_length=50
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Enter the contributor email", max_length=200
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Input name of the book", max_length=70),
                ),
                (
                    "publication_date",
                    models.DateField(verbose_name="Date the book wa published"),
                ),
                (
                    "isbn",
                    models.CharField(
                        max_length=20, verbose_name="ISBN number of the book"
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Reviews.publisher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bookcontributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("AUTHOR", "Author"),
                            ("CO_AUTHOR", "Co-Author"),
                            ("EDITOR", "Editor"),
                        ],
                        max_length=20,
                        verbose_name="The role the contributor has in the book",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Reviews.book"
                    ),
                ),
                (
                    "contributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Reviews.contributor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="contributor",
            field=models.ManyToManyField(
                through="Reviews.Bookcontributor", to="Reviews.contributor"
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(help_text="The Review text.")),
                (
                    "rating",
                    models.IntegerField(help_text="The rating the reviewer has given."),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time the review was created",
                    ),
                ),
                (
                    "date_edited",
                    models.DateTimeField(
                        help_text="The date the review was last edited", null=True
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        help_text="The book that is referred by this review",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Reviews.book",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
