# Generated by Django 5.0 on 2024-01-03 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Reviews", "0002_contributor_book_bookcontributor_book_contributor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookcontributor",
            name="contributor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="Reviews.contributor"
            ),
        ),
    ]
